sudo: false
language: node_js
node_js:
- 'node'
- '6'
env:
- TSI2_LING7='build'
- TSI2_LING7='test'
- TSI2_LING7='check'
branches:
  only:
  - master
script:
- echo npm run $TSI2_LING7
- npm run $TSI2_LING7
